name:                cswk-hurtle
version:             0.1.0.0
license:             "AllRightsReserved"
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2024 Alex Dixon"

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- parser-combinators
- gloss
- gloss-juicy
- mtl 

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans 
- -Wno-missing-export-lists

language: GHC2021

default-extensions: LambdaCase

library:
  source-dirs:
    - src
    # - src/hatch

executable: 
  main:                Main.hs
  source-dirs:         app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - cswk-hurtle

tests:
  cswk-hurtle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cswk-hurtle
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-reporter-muffled
    - random
    - ansi-terminal
    - QuickCheck
    - containers
    - cryptohash-md5
    - bytestring
    - directory
    - filepath
